### ISSUE TITLE
Get the error when running run_seg_gui.py

### ISSUE THREAD

**Issue by chengyangfu** [Jumpat/SegmentAnythingin3D#17]
Hi! 
   First, thanks for releasing the code! 
   I got a problem when running `run_seg_gui.py`.  After clicking `start training` bottom, this error message poped out: 
   
 ```  
Traceback (most recent call last):
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
    ctx.run(
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/SegmentAnythingin3D/lib/gui.py", line 326, in start_training
    self.Seg3d.train_step(self.train_idx, sam_mask=ctx['masks'][ctx['select_mask_id']])
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 189, in train_step
    self.inverse(seg_m, sam_mask)
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 176, in inverse
    optim(self.optimizer, loss, model=self.render_viewpoints_kwargs['model'])
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 550, in optim
    loss.backward()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 320, 320, 320]] is at version 2; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

Looks like this is a library issue. Wondering any body has the idea to solve this?

**Comment by chengyangfu** [comment]
Sorry. Copy and paste the wrong error message. 

This is the correct version: 

```
Traceback (most recent call last):
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/dash/dash.py", line 1265, in dispatch
    ctx.run(
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/SegmentAnythingin3D/lib/gui.py", line 326, in start_training
    self.Seg3d.train_step(self.train_idx, sam_mask=ctx['masks'][ctx['select_mask_id']])
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 189, in train_step
    self.inverse(seg_m, sam_mask)
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 176, in inverse
    optim(self.optimizer, loss, model=self.render_viewpoints_kwargs['model'])
  File "/home/SegmentAnythingin3D/lib/sam3d.py", line 550, in optim
    loss.backward()
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/SegmentAnythingin3D/sa3d/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 320, 320, 320]] is at version 2; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by chengyangfu** [comment]
Okay. This is my mistake. 

After running: 
```
python run.py --config=configs/nerf_unbounded/garden.py --stop_at=20000 --render_video --i_weights=10000
```
When running the gui part: 
Need to use ```seg_garden.py``` instead of ```garden.py```
``` 
python run_seg_gui.py  --config=configs/nerf_unbounded/seg_garden.py --segment --sp_name=_gui --num_prompts=20  --render_opt=train --save_ckpt
```

**Comment by Jumpat** [comment]
Yes, since the creation of the model and optimizer relies on the config file. We may fix these dirty code in our future modification🫣.
