### ISSUE TITLE
 No module named 'addict'

### ISSUE THREAD

**Issue by assissanliu** [Jumpat/SegmentAnythingin3D#30]
Traceback (most recent call last):
  File "G:\neural code\SegmentAnythingin3D-main\run_seg_gui.py", line 11, in <module>
    from lib.config_loader import Config
  File "G:\neural code\SegmentAnythingin3D-main\lib\config_loader.py", line 18, in <module>
    from addict import Dict
ModuleNotFoundError: No module named 'addict'

why？是提示没有数据集吗

**Comment by Zanue** [comment]
Try `pip install addict` to install the `addict` package?

**Comment by assissanliu** [comment]
File "G:\neural code\SegmentAnythingin3D-main\run.py", line 18, in <module>
    from lib import utils, dmpigo
  File "G:\neural code\SegmentAnythingin3D-main\lib\utils.py", line 10, in <module>
    from lib import seg_dvgo as dvgo
  File "G:\neural code\SegmentAnythingin3D-main\lib\seg_dvgo.py", line 12, in <module>
    from . import grid
  File "G:\neural code\SegmentAnythingin3D-main\lib\grid.py", line 13, in <module>
    render_utils_cuda = load(
  File "G:\neural code\SegmentAnythingin3D-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "G:\neural code\SegmentAnythingin3D-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "G:\neural code\SegmentAnythingin3D-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1524, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "G:\neural code\SegmentAnythingin3D-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1922, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "G:\neural code\SegmentAnythingin3D-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1694, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
How can I resolve this question

**Comment by Zanue** [comment]
There seems to be a driver / cuda mismatch. Refer to [this issue](https://github.com/pytorch/extension-cpp/issues/71#issuecomment-1137310884).
