### ISSUE TITLE
(nerfstudio version)AttributeError: 'SA3DTrainer' object has no attribute 'is_training'

### ISSUE THREAD

**Issue by ZhangXinPuHuo** [Jumpat/SegmentAnythingin3D#41]
When I run the nerfstudio version SA3D 

Traceback (most recent call last):
  File "/root/miniconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/root/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/root/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/root/tmp/SegmentAnythingin3D/sa3d/sa3d_trainer.py", line 211, in train
    while not self.is_training:
AttributeError: 'SA3DTrainer' object has no attribute 'is_training'

I noticed that neither the 'SA3DTrainer' class nor its parent class, 'nerfstudio.engine.trainer', has the attribute 'is_training'
How can I solve this problem.

**Comment by Zanue** [comment]
What is your nerfstudio version? I recommand `nerfstudio==0.2.0` .

**Comment by ZhangXinPuHuo** [comment]
I am using 0.3.4.I found that it using 'is_training' in 0.2.0 . but in 0.3.4 ,it changed to 'training_state' to represent the training status.
