### ISSUE TITLE
Failed to build torch_scatter and Grounding-Dino

### ISSUE THREAD

**Issue by RobotiX101** [Jumpat/SegmentAnythingin3D#42]
Docker images: 11.3.1-cudnn8-devel-ubuntu20.04

use `pip3 install -r requirements.txt`

while building torch_scatter, first error occurs:  `No module named torch`.

then I choose to manually install torch==1.12.1。and delete torch_scatter's version forcement in requirements and go on.

another error occurs, torch_scatter throw  `The detected CUDA version (11.3) mismatches the version that was used to compile PyTorch (10.2). Please make sure to use the same CUDA versions.`

the same error occurs while build Grounding Dino as below:

_____________________________________________________________
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/setup.py'"'"'; __file__='"'"'/NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/
    Complete output (56 lines):
    Building wheel groundingdino-0.1.0
    Compiling with CUDA
    running develop
    running egg_info
    writing groundingdino.egg-info/PKG-INFO
    writing dependency_links to groundingdino.egg-info/dependency_links.txt
    writing requirements to groundingdino.egg-info/requires.txt
    writing top-level names to groundingdino.egg-info/top_level.txt
    reading manifest file 'groundingdino.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'groundingdino.egg-info/SOURCES.txt'
    running build_ext
    /usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/setup.py", line 192, in <module>
        setup(
      File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 992, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 992, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
        self._check_cuda_version(compiler_name, compiler_version)
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
        raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
    RuntimeError:
    The detected CUDA version (11.3) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/setup.py'"'"'; __file__='"'"'/NeRF/SegmentAnythingin3D/dependencies/sam_ckpt/GroundingDINO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output

——————————————————————————————————————————————
which cuda version do I need to build this work?

**Comment by Jumpat** [comment]
Hello! The CUDA version is 11.7 in our environment.
