### ISSUE TITLE
使用自己的数据，出现错误RuntimeError: grid_sampler(): expected input to have non-empty spatial dimensions, but input has sizes [1, 1, 15920, 1940, 0] with dimension 4 being empty

### ISSUE THREAD

**Issue by zhangdandan-git** [Jumpat/SegmentAnythingin3D#94]
真的非常感谢你们的工作，这对我自己的一些研究实验很有帮助。
我已经将自己的数据tbike按照LLFF格式准备，
data/nerf_llff_data/tbike包括：
images
sparse
database.db
poses_bounds.npy

我现在使用自己的数据集运行时是遇到一些问题 :
Python run.py --config=configs/llff/tbike.py --stop_at=20000 --render_video --i_weights=10000

Traceback (most recent call last):
  File "..../SA3D/run.py", line 700, in <module>
    train(args, cfg, data_dict)
  File "..../SA3D/run.py", line 629, in train
    scene_rep_reconstruction(
  File ".../SA3D/run.py", line 496, in scene_rep_reconstruction
    render_result = model(
  File ".../sa3d2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../SA3D/lib/dvgo.py", line 348, in forward
    density = self.density(ray_pts)
  File ".../sa3d2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../seg/SA3D/lib/grid.py", line 57, in forward
    out = F.grid_sample(self.grid, ind_norm, mode='bilinear', align_corners=True)
  File "..../sa3d2/lib/python3.10/site-packages/torch/nn/functional.py", line 4223, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected input to have non-empty spatial dimensions, but input has sizes [1, 1, 15920, 1940, 0] with dimension 4 being empty

希望您能帮忙解答！

**Comment by Jumpat** [comment]
你好，请检查下self.grid的尺寸，并检查self.grid的创建，这可能是由于空间尺寸（长宽高）过于不均衡导致的，你的数据集colmap匹配能够顺利进行吗，匹配后得到的点云能够成功可视化吗？
